### PR TITLE
Track objective constant in n.objective_constant

### LINKED ISSUE #155: add objective constant as `n.objective_constant`
The cost of existing infrastructure is removed from the objective function as it is a constant. It should nonetheless be easily accessible. I would propose to attach to the network in addition to `n.objective` this constant as `n.objective_constant`.

### PR DESCRIPTION
**Pull request by FabianHofmann**
Closes #155 

## Changes proposed in this Pull Request
See issue

## Checklist

- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
@fneum you know where the dconf comes from? It somehow sneaked in

**Comment by fneum** [comment]
That was me yesterday. I just noticed.

**Comment by fneum** [comment]
Removed it already in the master branch.

**Comment by FabianHofmann** [comment]
Alright, then there should be no problem

**Pull request merged**
