### PR TITLE
add compatibility with pyomo 5.7.0

### LINKED ISSUE #186: AttributeError: 'SolverStatus' object has no attribute 'key'
## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

Generate a network using the example in scigrid-de/scigrid-with-load-gen-trafos/. On calling the function lopf() on a pyPSA network object get the following error call stack:
Screen Shot 2020-06-25 at 11 28 10 AM

The network is created by passing the example folder to the Network object. 
 
## Error Message

Output of conda list
```
# packages in environment at /opt/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.02                  py37_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  custom                   py37_1  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.12                   py37_0  
anaconda-project          0.8.4                      py_0  
appdirs                   1.4.3            py37h28b3542_0  
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                    py37_0  
appscript                 1.1.0            py37h1de35cc_0  
argh                      0.26.2                   py37_0  
asn1crypto                1.3.0                    py37_0  
astroid                   2.3.3                    py37_0  
astropy                   4.0.1.post1      py37h01d97ff_1  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autopep8                  1.4.4                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.1                    py37_0  
bitarray                  1.2.2            py37haf1e3a3_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.5                      py_0  
blosc                     1.19.0               hab81aa3_0  
bokeh                     2.1.0                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.3.2            py37hf1fa96c_1  
brotlipy                  0.7.0           py37haf1e3a3_1000  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2020.1.1                      0  
cartopy                   0.17.0           py37h1d108a8_1  
certifi                   2020.6.20                py37_0  
cffi                      1.14.0           py37hb5b8e2f_0  
cftime                    1.1.2            py37h776bbcc_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.2                      py_0  
cloudpickle               1.4.1                      py_0  
clyent                    1.2.2                    py37_1  
coincbc                   2.10.3               h7a5a08d_3    conda-forge
colorama                  0.4.3                      py_0  
conda                     4.8.3                    py37_0  
conda-build               3.18.11                  py37_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.6.1            py37h1de35cc_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.6.0.post1                py_0  
cryptography              2.9.2            py37ha12b0ac_0  
curl                      7.69.1               ha441bb4_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.20          py37hb1e8313_0  
cytoolz                   0.10.1           py37h1de35cc_0  
dask                      2.19.0                     py_0  
dask-core                 2.19.0                     py_0  
dbus                      1.13.14              h517e14e_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20181111                   py_0  
distributed               2.19.0                   py37_0  
docutils                  0.16                     py37_1  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.1.0            py37h1de35cc_0  
filelock                  3.0.12                     py_0  
flake8                    3.7.9                    py37_0  
flask                     1.1.2                      py_0  
freetype                  2.10.2               ha233b18_0  
fsspec                    0.7.4                      py_0  
future                    0.18.2                   py37_1  
geos                      3.8.0                hb1e8313_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    20.6.2           py37haf1e3a3_0  
glib                      2.63.1               hd977a24_0  
glob2                     0.7                        py_0  
glpk                      4.65              h65ac59c_1002    conda-forge
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
greenlet                  0.4.16           py37haf1e3a3_0  
h5py                      2.10.0           py37h3134771_0  
hdf4                      4.2.13               h39711bb_2  
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.0.1                    py37_0  
hypothesis                5.16.1                     py_0  
icu                       58.2                 h0a44026_3  
idna                      2.9                        py_1  
imageio                   2.8.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        1.6.1                    py37_0  
importlib_metadata        1.6.1                         0  
intel-openmp              2019.4                      233  
intervaltree              3.0.2                      py_0  
ipykernel                 5.3.0            py37h5ca1d4c_0  
ipython                   7.15.0                   py37_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.15.2                   py37_0  
jinja2                    2.11.2                     py_0  
joblib                    0.15.1                     py_0  
jpeg                      9b                   he5867d9_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.3                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                2.1.4                      py_1  
jupyterlab_server         1.1.5                      py_0  
keyring                   21.1.1                   py37_2  
kiwisolver                1.2.0            py37h04f5b5a_0  
krb5                      1.17.1               hddcf347_0  
lazy-object-proxy         1.5.0            py37haf1e3a3_0  
libarchive                3.4.2                haa3ed63_0  
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libcurl                   7.69.1               h051b688_0  
libcxx                    10.0.0                        1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20191231         haf1e3a3_0  
libffi                    3.2.1                h0a44026_6  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
liblapack                 3.8.0                    14_mkl    conda-forge
liblief                   0.10.1               h0a44026_0  
libnetcdf                 4.7.3                he3b6227_0  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h0a44026_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.1.0                hcb84e12_1  
libxml2                   2.9.10               h3b9e6c8_1  
libxslt                   1.1.34               h83b36ba_0  
llvm-openmp               10.0.0               h28b9765_0  
llvmlite                  0.32.1           py37h8c7ce04_0  
locket                    0.2.0                    py37_1  
lxml                      4.5.1            py37h63b7cb6_0  
lz4-c                     1.9.2                h0a44026_0  
lzo                       2.10                 h1de35cc_2  
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.2.2                         0  
matplotlib-base           3.2.2            py37h5670ca0_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.1.0            py37hc64f4ea_0  
mkl_random                1.1.1            py37h959d312_0  
mock                      4.0.2                      py_0  
more-itertools            8.4.0                      py_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            1.0.0            py37h04f5b5a_1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.7                      py_0  
ncurses                   6.2                  h0a44026_1  
netcdf4                   1.5.3            py37h28545a2_0  
networkx                  2.4                        py_0  
nltk                      3.5                        py_0  
nose                      1.3.7                    py37_2  
notebook                  6.0.3                    py37_0  
numba                     0.49.1           py37h86efe34_0  
numexpr                   2.7.1            py37hce01a72_0  
numpy                     1.18.5           py37h1da2735_0  
numpy-base                1.18.5           py37h3304bdc_0  
numpydoc                  1.0.0                      py_0  
olefile                   0.46                     py37_0  
openpyxl                  3.0.3                      py_0  
openssl                   1.1.1g               h1de35cc_0  
owslib                    0.19.2                     py_1  
packaging                 20.4                       py_0  
pandas                    1.0.5            py37h959d312_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.5.2                      py_0  
partd                     1.1.0                      py_0  
path                      13.1.0                   py37_0  
path.py                   12.4.0                        0  
pathlib2                  2.3.5                    py37_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py37_0  
pcre                      8.44                 hb1e8313_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.1.2            py37h4655f20_0  
pip                       20.1.1                   py37_1  
pkginfo                   1.5.0.1                  py37_0  
pluggy                    0.13.1                   py37_0  
ply                       3.11                     py37_0  
proj                      7.0.1                hdb716b3_1  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.5                      py_0  
prompt_toolkit            3.0.5                         0  
psutil                    5.7.0            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.2                      py_0  
py-lief                   0.10.1           py37haf313ee_0  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.20                       py_0  
pycrypto                  2.6.1           py37haf1e3a3_10  
pycurl                    7.43.0.5         py37ha12b0ac_0  
pydocstyle                5.0.2                      py_0  
pyepsg                    0.4.0                    py37_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.6.1                      py_0  
pykdtree                  1.3.1            py37h1d22016_2  
pylint                    2.4.4                    py37_0  
pyodbc                    4.0.30           py37h0a44026_0  
pyomo                     5.7              py37h4b3a949_2    conda-forge
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.7                      py_0  
pyproj                    2.6.1.post1      py37ha9dc991_1  
pypsa                     0.17.0             pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.16.0           py37h1de35cc_0  
pyshp                     2.1.0                      py_0  
pysocks                   1.7.1                    py37_0  
pytables                  3.6.1            py37h5bccee9_0  
pytest                    5.4.3                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.8.0                      py_0  
pytest-astropy-header     0.1.2                      py_0  
pytest-doctestplus        0.7.0                      py_0  
pytest-openfiles          0.5.0                      py_0  
pytest-remotedata         0.3.2                    py37_0  
python                    3.7.7           hc70fcce_0_cpython  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_0  
python-language-server    0.31.10                  py37_0  
python-libarchive-c       2.9                        py_0  
python.app                2                       py37_10  
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                     py_0  
pyutilib                  6.0.0              pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py37h1de35cc_0  
pyyaml                    5.3.1            py37h1de35cc_0  
pyzmq                     19.0.1           py37hb1e8313_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.7.2                      py_0  
qtconsole                 4.7.5                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h1de35cc_0  
regex                     2020.5.14        py37haf1e3a3_0  
requests                  2.24.0                     py_0  
ripgrep                   11.0.2               he32d670_0  
rope                      0.17.0                     py_0  
rtree                     0.9.4                    py37_1  
ruamel_yaml               0.15.87          py37h1de35cc_0  
scikit-image              0.16.2           py37h6c726b0_0  
scikit-learn              0.23.1           py37h603561c_0  
scipy                     1.5.0            py37h912ce22_0  
seaborn                   0.10.1                     py_0  
send2trash                1.5.0                    py37_0  
setuptools                47.3.1                   py37_0  
shapely                   1.7.0            py37h727f1cc_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.15.0                     py_0  
snappy                    1.1.8                hb1e8313_0  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.1.1                      py_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.2                      py_0  
spyder                    4.1.3                    py37_0  
spyder-kernels            1.9.1                    py37_0  
sqlalchemy                1.3.17           py37haf1e3a3_0  
sqlite                    3.32.3               hffcf06c_0  
statsmodels               0.11.1           py37haf1e3a3_0  
sympy                     1.6                      py37_0  
tbb                       2020.0               h04f5b5a_0  
tblib                     1.6.0                      py_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hb0a8c7a_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.4            py37h1de35cc_1  
tqdm                      4.46.1                     py_0  
traitlets                 4.3.3                    py37_0  
typing_extensions         3.7.4.2                    py_0  
ujson                     1.35             py37h1de35cc_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.25.9                     py_0  
watchdog                  0.10.2           py37h1de35cc_0  
wcwidth                   0.2.4                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.12.1           py37h1de35cc_1  
wurlitzer                 2.0.0                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.2.9                      py_0  
xlwings                   0.19.4                   py37_0  
xlwt                      1.3.0                    py37_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.1.7                hc338f04_2  
yapf                      0.29.0                     py_0  
zeromq                    4.3.2                hb1e8313_2  
zict                      2.0.0                      py_0  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zope                      1.0                      py37_1  
zope.event                4.4                      py37_0  
zope.interface            4.7.1            py37h1de35cc_0  
zstd                      1.4.4                h1990bb4_3





```

### PR DESCRIPTION
**Pull request by fneum**
Closes #186.

## Changes proposed in this Pull Request

Add compatibility for pyomo v5.7.0.

There were some (for our use breaking) changes in the newest version due to
https://github.com/Pyomo/pyomo/pull/1506 as described in the issue above. It replaces use of PyUtilib's Enum with the built-in Python enum package. The new SolverStatus class does not have a `key` attribute any longer.

The relevant lines in pyomo are here:
https://github.com/Pyomo/pyomo/blob/master/pyomo/opt/results/solver.py#L20-L82

## Checklist

~- [ ] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.~
~- [ ] Unit tests for new features were added (if applicable).~
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.

### CODE REVIEW

**Comment by fneum** [comment]
@FabianHofmann @nworbmot fine with the minimum pyomo requirement?

If yes, we could simplify this code: https://github.com/PyPSA/PyPSA/blob/649d1577088b0c90db29dd895315455cae44c895/pypsa/opt.py#L147-L172

However, the more inclusive solution would be to add another version conditional here https://github.com/PyPSA/PyPSA/blob/649d1577088b0c90db29dd895315455cae44c895/pypsa/opf.py#L1586-L1587

BTW, there are some workarounds for versions of pandas which the environment.yaml/setup.py does not allow anymore (e.g. `pandas<=0.18.0`, for another PR):
- https://github.com/PyPSA/PyPSA/blob/649d1577088b0c90db29dd895315455cae44c895/pypsa/opf.py#L1234-L1236
- https://github.com/PyPSA/PyPSA/blob/649d1577088b0c90db29dd895315455cae44c895/pypsa/components.py#L392-L393

**Comment by FabianHofmann** [comment]
> @FabianHofmann @nworbmot fine with the minimum pyomo requirement?
> 
> If yes, we could simplify this code:
...

Yes, I'd definitely agree

**Comment by fneum** [comment]
Ups, last commit is not correct!

**Comment by fneum** [comment]
Hopefully last re-request to review :)

**Pull request merged**
