### PR TITLE
refactor: `statistics.py` structure

### PR DESCRIPTION
**Pull request by lkstrp**
- make functions which are internal actually internal
- move grouper methods to grouper

### CODE REVIEW

**Comment by FabianHofmann** [comment]
I am actually not sure, if all the `get` functions are actually "internal". I think that an import from `pypsa.statistics` is not uncommon, as for example here https://github.com/PyPSA/pypsa-eur/pull/921/files#diff-6dafdba3772c0812a6a645c461f092bdbf7e0d7447be19ec5ea4c071e33e5302

Perhaps we make this non-breaking?

**Comment by euronion** [comment]
> I am actually not sure, if all the `get` functions are actually "internal". I think that an import from `pypsa.statistics` is not uncommon, as for example here https://github.com/PyPSA/pypsa-eur/pull/921/files#diff-6dafdba3772c0812a6a645c461f092bdbf7e0d7447be19ec5ea4c071e33e5302
> 
> Perhaps we make this non-breaking?

I second.

**Comment by lkstrp** [comment]
You both mean the groupers? I did not make them internal.
But there is no reason to have them that often and not consistent in the API:
- via `pypsa.statistics.Groupers.get_carriers`
- via `pypsa.statistics.get_carriers`
- via `n.statistics.groupers.get_carriers`

What do you think about keeping only
- via `pypsa.statistics.groupers.get_carriers`
- via `n.statistics.groupers.get_carriers`

and deprecating `pypsa.statistics.get_carriers` instead of removing?

**Comment by FabianHofmann** [comment]
> You both mean the groupers? I did not make them internal. But there is no reason to have them that often and not consistent in the API:
> 
> * via `pypsa.statistics.Groupers.get_carriers`
> * via `pypsa.statistics.get_carriers`
> * via `n.statistics.groupers.get_carriers`
> 
> What do you think about keeping only
> 
> * via `pypsa.statistics.groupers.get_carriers`
> * via `n.statistics.groupers.get_carriers`
> 
> and deprecating `pypsa.statistics.get_carriers` instead of removing?

yes, that sounds like a good middle ground. Initially, I was referring to the non-strict grouper functions like  `_get_transmission_branches` which now moved to internal, but will very likely be used as official functions. Perhaps we move them to descriptors.py and keep them as official?

**Comment by lkstrp** [comment]
It would make sense too pull #885 and #886 by @p-glaum first. I think they are good to go?

**Comment by p-glaum** [comment]
> It would make sense too pull #885 and #886 by @p-glaum first. I think they are good to go?

I guess #885 is ready to merge if there are no further comments and #886 still needs someone to review.

**Comment by fneum** [comment]
I just reviewed #885 and #886. Both require some changes or clarifications.

**Comment by fneum** [comment]
#885 and #886 are now both merged

**Comment by fneum** [comment]
Revise and merge after #1075, #1044

**Pull request closed without merging**
