### PR TITLE
Frontend stats

### LINKED ISSUE #333: Frontend stats
in `pypsa.stats`

- curtailment
- market value mv_s = $sum_{t} \lambda_t g_{s,t} / sum_{t,s} g_{s,t}$
- congestion rent
- revenue
- n.nom_opt() -> pd.Series(index=[component, carrier], values=nom_opt)

ask over mailing list

### PR DESCRIPTION
**Pull request by p-glaum**
Closes #333 

## Changes proposed in this Pull Request

Add frontend stats:
- [x] curtailment
- [x] capital cost and operational cost 
- [x] market value 
- [x] congestion rent
- [x] revenue
- [x] generation
- [x] n.nom_opt() -> pd.Series(index=[component, carrier], values=nom_opt)

If you have more stats you would like to add, feel free to add them in the comments.

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
Hey @p-glaum, I rewrote some parts to make it more modular. Now it is possible to group by carrier or carrier and bus (or user defined grouping). The optimized flag is not needed anymore as attribute which cannot be extracted are now simply ignored. Could you have a test and a look at the doc strings? 

Also note: 
```python
n.statistics()
```
now gives a full table of all the available methods.

**Comment by p-glaum** [comment]
Hi @FabianHofmann,
looks really nice. I like the modularization you implemented. I noticed that the default values for aggregate_time and aggregate_groups is None for the class methods. This lead to an error when only running e.g. n.statistics.revenue(). I also made some minor changes to the docstrings.
Also, I was wondering what happened to the method congestion_rent?

**Comment by FabianHofmann** [comment]
Great, thanks @p-glaum,I thought the None defaults would be captured by underlying function, but anyhow having a not None default is better. The congestion rent moved into the revenue function, as it is in principal the same. Could add an explanation in the doc-string though.

**Comment by p-glaum** [comment]
@fneum, do you want to have a look as well?

**Pull request merged**
