### PR TITLE
optimize: speed up large model creation

### PR DESCRIPTION
**Pull request by FabianHofmann**
Speeds up model creation for spatially large models. 

Example: 181 sector coupled model with 24 snapshots. Creation time reduced from 80 sec to 3 sec.

### CODE REVIEW

**Review by fneum — COMMENTED** [review]
Neat!

Should `skip_isolated_buses=True` be the default?

Should we also pass this in `linopf` and `pyomo` versions?

**Comment by FabianHofmann** [comment]
I didn't want to change the default behavior, that's why I left it. We could add a warning that in future versions this will be changed. Yes, forwarding seems to be reasonable.

**Review by fneum — APPROVED** [review]

**Comment by fneum** [comment]
But something is going wrong with tests. Is this related to this PR?

**Comment by FabianHofmann** [comment]
It threw error with the linopf code. Can also introduce later if needed.

**Comment by fneum** [comment]
:+1:

**Pull request merged**
