### PR TITLE
add example models using PyPSA

### PR DESCRIPTION
**Pull request by lisazeyen**
Closes # (if applicable).

## Changes proposed in this Pull Request
 Add example open-source models using PyPSA

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Review by fneum — CHANGES_REQUESTED** [review]
Nice, but a few syntax changes are necessary:

Hyperlinks in .rst go like this: `abcdf <https://...>`_

The section also needs to be added to the `toctree` in `doc/index.rst` (~ line 107)

**Comment by lisazeyen** [comment]
ah yes, should have tested it more carefully, thanks @fneum . Links should work now and the section is also added to the index.

**Comment by fneum** [comment]
Ah, sorry @lisazeyen, the hyperlinks still don't work because my example was not displayed in a helpful way. Second try:

```
`abcdf <https://...>`_
```

**Comment by fneum** [comment]
The CI will also build the documentation for this PR if you click on the details of the readthedocs check

**Pull request merged**
