### PR TITLE
Fix linopy implementation of nominal capacity per-bus/carrier constraints

### LINKED ISSUE #523: `nom_max_{carrier}` limits all extendable components regardless of carrier
Will also quickly look into a fix myself today.

Affects new `global_constraints.py` linopy-based implementation.

## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

### PR DESCRIPTION
**Pull request by coroa**
Closes #523 .

## Changes proposed in this Pull Request

The linopy implementation affected one_port_components of all carriers not only the selected. Also the period selection was broken.

This PR fixes those.

## Checklist

- [ ] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [ ] Unit tests for new features were added (if applicable).
- [ ] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [ ] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Comment by coroa** [comment]
Well, while testing this, i am finding that not much of this functionality ever worked reliably and i like the `n.global_constraints` like constraint specification used by the `linopt` type optimisation more.

Can I scrap this `nom_max_...` feature in favour of `n.global_constraints` `tech_capacity_expansion_limit`?

**Comment by FabianHofmann** [comment]
> Well, while testing this, i am finding that not much of this functionality ever worked reliably and i like the `n.global_constraints` like constraint specification used by the `linopf` optimisation more.
> 
> Can I scrap this `nom_max_...` feature in favour of `n.global_constraints` `tech_capacity_expansion_limit`?

Yes, that would be cleaner. However, I just saw that `tech_capacity_expansion_limit` is not yet implemented for the linopy implementation...

I would preferably deprecate the functionality first, before removing in the next major release. Or we remove it directly and add a warning if users still have corresponding columns in the bus dataframe.

**Comment by coroa** [comment]
Added the implementation

**Review by FabianHofmann — APPROVED** [review]

**Comment by FabianHofmann** [comment]
Thanks @coroa

**Pull request merged**
