### PR TITLE
add quadratic marginal cost for stores and storage units

### PR DESCRIPTION
**Pull request by fneum**

### CODE REVIEW

**Comment by coroa** [comment]
What's the plan for the implementation in the objective function? is there already linopy support for a quadratic objective?

**Comment by fneum** [comment]
It's already done! Both in linopy and PyPSA.

**Comment by coroa** [comment]
Ah very, good!

https://github.com/PyPSA/PyPSA/blob/6ef116fe73d19062610647479cf50c09d165f1ee/pypsa/optimization/optimize.py#L129-L140

Do you know by any chance whether non-diagonal quadratic objective function parameters are also supported by linopy now, in the spirit of:

v A v where A is a quadratic matrix and v the vector of variables?

**Comment by FabianHofmann** [comment]
Yes they are :)

**Pull request merged**
