### PR TITLE
Multi investment review

### PR DESCRIPTION
**Pull request by FabianHofmann**
Closes #211 #257 #36 

## Changes proposed in this Pull Request

This is the finished review of the PR #257, some of the implementation was refactored and enhanced from a performance point of view, some unnecessary changes were removed. But most importantly, many unit tests were added which built the bases for most changes.  

As discussed with @lisazeyen, I pull request directly against the master branch to shorten the process a bit. 

An example notebook was added (also to the docs). It explains the basics of the new features. You find it in examples/notebooks/multi-investment-optimisation.ipynb. 

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.

### CODE REVIEW

**Comment by lisazeyen** [comment]
That looks really great. It is a nice solution with the `mask` when defining variables. I only pushed minor changes (in example script, opt.py and fixing one typo). I further added the possibility to define a growth limit (e.g. 10 GW) for a given carrier (e.g. "onwind") between investment periods. This only applies to extendable assets if the lopf is called with `multi_investment_periods=True` and a limit is define in` n.carriers.max_growth`

**Review by lisazeyen — APPROVED** [review]
Looks great! Sorry, I have pushed directly to the branch, but I only had minor suggestion for changes.

**Comment by FabianHofmann** [comment]
Great @lisazeyen! Good job!

**Comment by fneum** [comment]
:partying_face: :tada:

**Pull request merged**
