### PR TITLE
merge instead of concat

### PR DESCRIPTION
**Pull request by lisazeyen**
Closes # (if applicable).

## Changes proposed in this Pull Request

This PR proposes a formulation which consumes less memory when calling the function `get_switchable_as_dense` especially with large dataframes, concating the static and varying dataframes consumes a lot of memory.
## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
@lisazeyen you think the `del` calls are necessary? garbage collection of python should be taking care of it.

**Comment by FabianHofmann** [comment]
@lisazeyen I looked up the functionality of `pd.merge`, and I have a semi-good gut feeling about using it. Could you perhaps try wether we could use something like this?

```python

    static = df.loc[fixed_i, attr]
    varying = pnl[attr].loc[snapshots, varying_i]
    return varying.assign(**static).reindex(columns=index)
```

and if that is perhaps memory efficient?

**Comment by lisazeyen** [comment]
> @lisazeyen I looked up the functionality of `pd.merge`, and I have a semi-good gut feeling about using it. Could you perhaps try wether we could use something like this?
> 
> ```python
>     static = df.loc[fixed_i, attr]
>     varying = pnl[attr].loc[snapshots, varying_i]
>     return varying.assign(**static).reindex(columns=index)
> ```
> 
> and if that is perhaps memory efficient?


 this would work as well, what are your suspicions about `pd.merge`?

**Comment by FabianHofmann** [comment]
my suspicion is that I don't understand it fully  :D 

my question would be why left_index and right_index? 
and why join=inner? this should only lead to returning the overlapping columns or? 

`pd.merge` is rather used for more complex operations where you have partially overlapping and distinct indexes and columns. But here the operation is quite clear: just add a couple of new columns with constant values. since this is a very basic function I would like to make it as clear as possible.

**Pull request merged**
