### PR TITLE
global_constraint: add operational limit constraint

### PR DESCRIPTION
**Pull request by FabianHofmann**
Analogous to `primary_energy_limit` but directly working on carrier output. This will help to replace some stores in pypsa-eur (sector-coupled) by light-weight constrained generators.

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Comment by fneum** [comment]
Can you explain a little more about how it works? I don't yet understand why it is better than a Store.

**Comment by FabianHofmann** [comment]
The reason is that modelling stores is quite extensive. You have intertemporal constraints with auxiliary variables (soc, charge, discharge). If you limit the total energy output of one single generator (or a generator carrier fleet) instead of setting up a store with an initial soc which depletes over time, you save a lot of complexity. So (reducing the generators) the constraint is just saying 

```math
\sum_{G \in \Theta, t} g_{G, t} <= limit
```
where $\Theta$ is the set of generators which belong to the carrier set in the global constraint.

**Review by fneum — APPROVED** [review]
Looks good! Nicely tested, so it was easy to review.

**Comment by fneum** [comment]
At some point, we need to update the documentation of the GlobalConstraint component:

https://pypsa.readthedocs.io/en/latest/components.html#global-constraints

**Comment by tintin305** [comment]
I don't see any place that caters for selecting investment_periods. Will this still need to be introduced as a parameter?

**Pull request merged**
