### PR TITLE
Add nominal bounds for bus & carrier

### PR DESCRIPTION
**Pull request by FabianHofmann**
## Changes proposed in this Pull Request

Support lower and upper capacity constraints per bus and carrier. With this feature the combined capacity of components of the same carrier at the same bus can be constrained by setting values in `n.buses['nom_max_{carrier}']` / `n.buses['nom_min_{carrier}']` (where carrier is a dummy for wind, solar etc. )

Test it with 

```
import pypsa
from pathlib import Path

n = pypsa.Network(str(Path(pypsa.__file__).parent.parent / 'examples'/
                      'ac-dc-meshed'/ 'ac-dc-data'))

n.add('Generator', 'Frankfurt Wind 2', bus='Frankfurt', capital_cost = 120,
      carrier='wind', p_nom_extendable=True)

n.buses.loc[['Frankfurt', 'Manchester'], 'nom_min_wind'] = 2000
n.buses.loc[['Frankfurt'],'nom_max_wind'] = 2200

n.lopf(pyomo=False)

print(n.generators.p_nom_opt)

```

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] ~Unit tests for new features were added (if applicable).~
- [x] ~Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).~
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.

### CODE REVIEW

**Review by fneum — CHANGES_REQUESTED** [review]
There's some code duplication in the two loops. I was wondering whether one could simply reduce this by looping over the senses:

```py
for bound, sense in [("max", "<="), ("min", ">=")]:
    for carrier in n.carriers.index:
        col = f'nom_{bound}_{carrier}'
...
        define_constraints(n, lhs, sense, rhs, 'Bus', 'mu_' + col)
```

The other difference is how limits at buses with no extendable components are handled:

Upper limits are less strict and handle exceptions:

```py
        lhs = lhs[lhs != '']
        rhs = rhs.reindex(lhs.index)
```

whereas lower bounds don't and are more restrictive

```py
        assert (lhs != '').all(), (
            f'No extendable components of carrier {carrier} on bus '
            f'{list(lhs[lhs == ""].index)}')
```

Would be nice to unify this, right?

**Comment by FabianHofmann** [comment]
Yes, indeed we can unify the two loops. Give me a second

**Comment by fneum** [comment]
If you merge the master, tests should pass.

While you are at it can you add documentation of `nom_max_{carrier}` to the component attributes at

https://github.com/PyPSA/PyPSA/blob/master/pypsa/component_attrs/buses.csv

?

**Comment by FabianHofmann** [comment]
> If you merge the master, tests should pass.
> 
> While you are at it can you add documentation of `nom_max_{carrier}` to the component attributes at
> 
> https://github.com/PyPSA/PyPSA/blob/master/pypsa/component_attrs/buses.csv
> 
> ?

Unfortunate that's will end up in a weird extra column, n.buses['nom_min_{carrier}'] (with exactly this name) when loading any network. So I wouldn't do it. Probably it makes more sense to add a proper example jupyter notebook how to use it.

**Comment by fneum** [comment]
> Unfortunate that's will end up in a weird extra column

Ah, I see. I just wanted this functionality documented somewhere else than in the release notes. An example would be fine. I think we could just use your example at the top of the PR.

**Review by fneum — APPROVED** [review]

**Pull request merged**
