### PR TITLE
cloud object storage io with cloudpathlib

### PR DESCRIPTION
**Pull request by ollie-bell**
Closes # (if applicable).

## Changes proposed in this Pull Request
Enable import and export directly from files in cloud object storage. Optional dependency on `cloudpathlib`, installable via `pypsa[cloudpath]`.

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Review by lkstrp — CHANGES_REQUESTED** [review]
This is a neat integration, thanks!
- I assume the `cloudpathlib.AnyPath` will handle all normal Paths or strings as well, just like `pathlib` would do?
- Could you add a very small note to the `path` argument in the the docstrings as well?
- And maybe also explicitly list AWS S3, Google Cloud Storage, and Azure Blob etc. in the docs section, so it can be found via search.

**Comment by ollie-bell** [comment]
> This is a neat integration, thanks!
> 
> * I assume the `cloudpathlib.AnyPath` will handle all normal Paths or strings as well, just like `pathlib` would do?
> * Could you add a very small note to the `path` argument in the the docstrings as well?
> * And maybe also explicitly list AWS S3, Google Cloud Storage, and Azure Blob etc. in the docs section, so it can be found via search.
> * And a small test would be great

Yep! When you give a string representing a local file to `AnyPath` it constructs a `pathlib.Path` object as normal.

I've added the documentation changes you requested.

Proper tests are unfortunately a bit tricky here, because it requires having a cloud storage bucket which you can authenticate to with read/write access. As far as I am aware there are no public buckets with write access to use for testing. It would be possible to set up a free tier / very low cost bucket to use for testing in CI only though, but this a bit cumbersome to maintain 😰

However, I have added a small test which checks that when local paths are used then pathlib.Path is instantiated as normal.

**Review by lkstrp — APPROVED** [review]
Great, thank you!

Just the pathlib check is fine.

**Comment by FabianHofmann** [comment]
very cool!

**Pull request merged**
