### PR TITLE
statistics: add bus_carrier argument

### PR DESCRIPTION
**Pull request by FabianHofmann**
* The statistics module now supports the consideration of multi-port links. An additional argument `bus_carrier` was added to the functions to select the components that are attached to buses of a certain carrier.

* The plotting routine now supports the plotting of a subset of buses/lines/links/transformers. This is useful for plotting only a subset of the network. Therefore, the arguments ``bus_sizes``, ``link_widths``, ``link_colors`` etc. do not require to contain the full set of indexes of a component.

* The statistics module now supports the consideration of investment periods. Therefore, as soon as ``n.snapshots`` is a MultiIndex, the statistics are calculated for each period in the first level of the index separately.

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Unit tests for new features were added (if applicable).
- [x] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
@p-glaum if you could have a final look, I am quite happy with it now...

**Comment by p-glaum** [comment]
cool! Yes ofc, I will take a look at it tomorrow.

**Comment by FabianHofmann** [comment]
@p-glaum are you fine with merging?

**Review by p-glaum — COMMENTED** [review]
Tested it in my plotting routines and everything worked fine :) I have nothing to comment.

**Comment by FabianHofmann** [comment]
thanks @p-glaum

**Pull request merged**
