### PR TITLE
plot: consistency between MultiIndex and Index bus sizes (closes #132)

### LINKED ISSUE #132: plot.py: area of bus_sizes is not consistent with MultiIndex versus regular Index
If you are plotting variable bus_sizes specified by pandas.Series `bus_sizes`, but no pie charts, the following ways of plotting give different bus areas:
`network.plot(...bus_sizes=bus_sizes...)`
(this defaults to standard matplotlib scatter) and
`bus_sizes.index = pd.MultiIndex.from_product([bus_sizes.index,["dummy"]])
network.plot(...bus_sizes=bus_sizes...)`
(this makes pie charts).
This was causing me problems matching the legend to the bus_sizes for H2 network plotting in PyPSA-Eur-Sec, see my fix here:
https://github.com/nworbmot/pypsa-eur-sec/commit/d4c6521aaf1f29d7fa8880ab42da4ced58e467aa
We should adjust this so the areas always come out the same.

### PR DESCRIPTION
**Pull request by fneum**
Closes #132 .

Achieve consistency of `bus_sizes` regardless of whether it has a `pd.MultiIndex` or `pd.Index`.
Substitutes `ax.scatter(...)` with `matplotlib.patches.Circle` (which is very similar to `matplotlib.patches.Wedge`). The unit of the radius is now, hence changed default `bus_size=0.01`. Also using `ax.set_aspect('equal')` to avoid squeezed circles.

Test with:

```python
import pypsa
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import pandas as pd

n = pypsa.Network("examples/scigrid-de/scigrid-with-load-gen-trafos/")

c = n.generators.groupby('bus').sum().p_nom

fig, ax = plt.subplots(figsize=(7,7), subplot_kw={"projection":ccrs.PlateCarree()})
n.plot(ax=ax, geomap=True, line_widths=0, bus_sizes=c/3e4);

c.index = pd.MultiIndex.from_product([c.index,["dummy"]])

fig, ax = plt.subplots(figsize=(7,7), subplot_kw={"projection":ccrs.PlateCarree()})
n.plot(ax=ax, geomap=True, line_widths=0, bus_sizes=c/3e4, bus_colors={'dummy': 'b'});
```

Also change projection, geomap, bus_colors, colormap for testing.

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.

### CODE REVIEW

**Comment by fneum** [comment]
Have to change `network` to `n` if #139 is merged first.

**Comment by FabianHofmann** [comment]
hey, I'm currently trying to figure out whether we could plot both cases using `ax.pie`. This would reduce the code and make it more accessible. 
Note that `ax.pie(1, radius=s)` also works. First argument does not have to be a list....

**Comment by fneum** [comment]
Now that would be even better if it works. Does pie work with colormaps?

**Comment by FabianHofmann** [comment]
yes, I don't see any support for colormaps, with the code of your PR it should however work

**Comment by FabianHofmann** [comment]
I had a look again, and the performance would actually be worse using ax.pie (as many other feature are implemented there as well). Let's go for this one

**Pull request merged**
