### PR TITLE
Add a standard line type to represent DC lines

### PR DESCRIPTION
**Pull request by ekatef**
Relates to #518 

## Changes proposed in this Pull Request

A standard line type was added to represent DC lines. Realistic values of active resistance per length `r_per_length` and rated current `i_nom` were taken from the cited reference. Artificial values of inductance `x` and capacitance `c` were defined to represent a DC line.

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [ ] Unit tests for new features were added (if applicable).
- [ ] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Comment by fneum** [comment]
@ekatef, thanks for this proposal!

A couple of points, then it can go in:

- could you provide a link for the source?
- could you give a more specific name for the type of DC cable referenced?
- non-applicable values should be empty, not 'NA' or '0.0`.
- could you squash your commits on this branch down to 1 or 2?

**Comment by FabianHofmann** [comment]
This looks good. @ekatef if you are done, I would just squash-merge it

**Comment by ekatef** [comment]
@fneum thanks a lot for reviewing it!

@FabianHofmann thank you for checking and merging :)

**Comment by FabianHofmann** [comment]
> @fneum thanks a lot for reviewing it!
> 
> @FabianHofmann thank you for checking and merging :)

Thank you @ekatef for the contribution!

**Pull request merged**
